#!/usr/bin/python3 -B
# Copyright 2018 Paul Ozog.  All rights reserved.
"""Stage an event for upload to S3. This should run as a filter in Zoneminder
using the www-data user. Use zms3-upload (from another user) to upload to S3.

"""

import argparse
import sys
import zms3

def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('input', help='Path to event directory')
    args = parser.parse_args()
    queue = zms3.StageQueue()
    queue.push(args.input)

if __name__ == '__main__':
    sys.exit(main())
